Cargo.lock, Cargo.toml
This will unblock the full migration of deno to indexmap 2.x
=> chore: bump indexmap to 2

src/lib.rs
Will fix .. https://github.com/denoland/deno/issues/20393.
<details>
<summary>
CLI patch:
</summary>
```diff
diff --git a/cli/args/mod.rs b/cli/args/mod.rs
index f82ed9a71..e6ada9453 100644
--- a/cli/args/mod.rs
+++ b/cli/args/mod.rs
@@ -1398,20 +1398,18 @@ fn resolve_files(
let mut result = maybe_files_config.unwrap_or_default();
if let Some(file_flags) = maybe_file_flags {
if !file_flags.include.is_empty() {
-      result.include = file_flags.include;
+      result.include = Some(file_flags.include);
}
if !file_flags.ignore.is_empty() {
result.exclude = file_flags.ignore;
}
}
// Now expand globs if there are any
-  if !result.include.is_empty() {
-    result.include = expand_globs(result.include)?;
-  }
-
-  if !result.exclude.is_empty() {
-    result.exclude = …
```
=> fix: make include fields options

src/lib.rs
We'd like to read feature flag from deno.json(c). This PR adds reading of ~~`features`~~ `unstable` field.
Related: https://github.com/denoland/deno/issues/20779
=> feat: add `unstable` field

src/lib.rs
This PR adds `precompile` as a valid value for the `jsx` setting in `deno.json`.
=> feat: Add support for jsx precompile transform setting

src/lib.rs
serde deserializes `null` for `Option<serde_json::Value>` as `None` instead of `Some(serde_json::Value::Null)` (which can't kind makes sense I think), so I just can't add a test for `"exports": null`
=> fix: error on 'null' key in exports

src/glob.rs
The error was missing what URL was failing.
=> fix: add context when failing to parse a URL

src/lib.rs
I might be refactoring how `deno/didChangeDenoConfiguration` works so it's more sensible, needs this.
=> feat: impl Eq on ConfigFileJson

src/glob.rs, src/lib.rs
Previously we wouldn't traverse any directories when there were no "includes". We hacked around this in the CLI, but this is a real fix.
=> feat: add `base` to `FilePatterns`

src/lib.rs
For https://github.com/denoland/deno/pull/21991.
Since we removed conditional unstable type-checking
we don't need these two.
=> refactor: remove unstable variants from TsTypeLib

Cargo.lock, Cargo.toml, src/lib.rs
We shouldn't have a bunch of different ways of doing this, so let's move this down here. It will also be useful in stuff like dnt.
See CLI PR here: https://github.com/denoland/deno/pull/22553
Part of https://github.com/denoland/deno/issues/22270
=> feat: ability to resolve import map

src/glob.rs
Reality of the situation in Deno:
1. `"exclude"` has higher precedence than `"include"`.
- A file in `"include"` will not be matched against if it's excluded.
2. `"include"` is a closed set.
- Files not in the include set are not included.
This change makes it more flexible by having the ability to opt out of excluded files. This can be achieved via negated globs in either "publish.exclude" or "exclude" (or "fmt.exclude", "exclude" for the fmt command).
Specifically for checking if a file is excluded for publishing we first check `"publish.include"` for a match, then:
1. We use the array of the config's "exclude" + "publish.exclude" (done in https://github.com/denoland/deno_config/pull/43)
2. Go through each entry in reverse.
1. If entry is matched as opted-in (ex. !/dist/), then we …
=> feat: improve improve/exclude

src/glob.rs
Ran into this when reviewing more scenarios.
1. Makes doing `!dist` work for unexcluding a directory.
2. Makes unexcluding sub dirs of excluded dirs work.
=> feat: unexcluding sub dirs of excluded dirs

src/glob.rs, src/lib.rs
Errors when someone does:
```
{
"exclude": [
"!dist/sub_dir/".
"dist/"
]
}
```
and tells them to swap the entries.
=> fix: handle invalid negations

src/lib.rs
Preserve comments that are in a task definition and expose them as part of the tasks config.
The code is still kinda gnarly, but here for review
=> feat: Collect comments attached to task definitions

src/glob.rs, src/lib.rs
In the CLI, some code is doing `serde_json::to_string` to get a hash of this config. We can just make these derive `Hash` instead.
=> fix: derive `Hash` on more structs

src/lib.rs
Reason: The upcoming `deno publish --version 0.1.0` or whatever flag might cause some deno.json files to not have a version in them.
=> fix: only consider name and exports for if is a package

src/deno_json/mod.rs
Reverts #57
This is going to be completely changed in https://github.com/denoland/deno_config/pull/58
So reverting this for now
=> Revert "fix: do not error for workspace members missing name or version (#57)"

src/workspace/discovery.rs, src/workspace/mod.rs
Aligns with cargo.
Changes it to not require `"."` in the workspace root and not surface diagnostics about it because we can tell if the root is a package by if it has name and exports fields.
Changes:
```json
{
"name": "@scope/root",
"version": "1.0.0",
"exports": "./mod.ts"
"workspace": [".", "./sub_package"]
}
```
To:
```json
{
"name": "@scope/root",
"version": "1.0.0",
"exports": "./mod.ts",
"workspace": ["./sub_package"]
}
```
=> feat: remove requirement to specify current file in members when workspace root config is package

src/deno_json/mod.rs, src/util.rs, src/workspace/discovery.rs, src/workspace/mod.rs, src/workspace/resolver.rs
This is better config discovery that isn't as confusing and cause issues like [this](https://twitter.com/DavidSherret/status/1791513568321380378).
Essentially now that we have workspaces, we can use the exact same rules for discovering deno.json files that we do for package.json files:
1. When discovering the configs it looks for both package.json and deno.json at the same time.
2. If we find a deno.json with a workspace we stop. If we find a package.json with a workspace, then we stop.
4. When not in a workspace, we stop on the first deno.json or first package.json
- If a deno.json is in a root folder, then it needs to reference the package.json as part of the workspace in order to be discovered
5. We allow finding both a deno.json and a package.json in the same folder. We allow both of …
=> feat: restore resolving config from multiple paths and combine config discovery

src/workspace/mod.rs
Use double quotes because that's what's used in the config file.
=> fix: use double quotes for field diagnostics and update question to statement

Cargo.lock, rust-toolchain.toml, src/deno_json/mod.rs, src/glob/collector.rs, src/glob/mod.rs, src/util.rs, src/workspace/discovery.rs, src/workspace/mod.rs, src/workspace/resolver.rs
Fixes a bug where things would fall apart when arguments were provided.
This now takes the CLI arguments and merges them in with the config in the different workspace members.
CLI PR: https://github.com/denoland/deno/pull/24447
Part of https://github.com/denoland/deno/issues/24422
=> fix: better cli file argument handling

src/glob/mod.rs, src/util.rs, src/workspace/discovery.rs, src/workspace/mod.rs
Closes https://github.com/denoland/deno_config/issues/67
=> feat: support wildcards in npm workspaces

src/deno_json/mod.rs, src/workspace/discovery.rs, src/workspace/mod.rs
This makes the naming clear as `"workspace": [...]` is shortform for `"workspace": { "members": [...] }` similar to cargo (https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html#creating-a-workspace) and leaves this open for future properties.
https://github.com/denoland/deno/issues/24456#issuecomment-2212195697
=> feat(deno_json): support "workspace" as an object

src/workspace/mod.rs, src/workspace/resolver.rs
This supports publishing jsr packages when the root is an npm workspace.
=> fix: support publishing jsr packages in an npm workspace

src/deno_json/mod.rs, src/workspace/mod.rs
I'm changing this to be conditionally provided to deno_graph in the CLI based on whether the graph kind is including types and so this should be more precise about what it's returning.
=> refactor: rename `to_maybe_imports()` to `to_compiler_option_types()`

src/deno_json/mod.rs
=> fix: deny unknown fields for workspace config

src/workspace/discovery.rs, src/workspace/mod.rs
This allows stopping auto-discovery in ancestor directories which could contain stuff like npm workspaces.
=> fix: allow empty workspace config

src/workspace/discovery.rs, src/workspace/mod.rs
This is a very rare edge case that causes similar lockfile churn issues to https://github.com/denoland/deno_config/pull/85
Say you have:
```
package.json
nested/member/package.json
nested/package.json
```
and the root package.json is a workspace with only nested/member/package.json. We shouldn't cause any lockfile churn in this case by discovering nested/package.json when executing with a cwd in nested/member
=> fix(npm): don't discover non-workspace configs between two members

src/workspace/resolver.rs
This was undocumented. I think we should remove it because it's not super useful and it's yet another complication to resolution. It's also conflating tags to mean something else. We're also going to support bare specifiers for package.json workspace members.
=> fix(npm): remove undocumented `workspace` tag special case

src/workspace/resolver.rs
For https://github.com/denoland/deno/issues/24605
=> fix(npm): resolve bare specifiers to package.json workspace members

src/deno_json/mod.rs
Makes creating these configs easier in the LSP on error.
We don't want to create a default implementation because the base of file patterns matters.
=> feat: add default_with_base methods

src/lib.rs, src/workspace/discovery.rs, src/workspace/mod.rs, src/workspace/resolver.rs
After this PR, I'll add a `Workspace` cache similar to the deno_json and package.json, which will help out in the LSP.
Closes https://github.com/denoland/deno_config/issues/93
=> refactor: separate WorkspaceContext and Workspace

src/workspace/discovery.rs, src/workspace/mod.rs
This adds a workspace cache for use by the LSP, but also there's a bug fix for another edge case. I'll point out the test and code that fixes the edge case.
=> feat: workspace cache

src/deno_json/mod.rs, src/lib.rs, src/workspace/discovery.rs, src/workspace/mod.rs, src/workspace/resolver.rs
1. Shift more methods down to `Workspace`
2. Combine `WorkspaceContext` and `WorkspaceMemberContext` into `WorkspaceDir`
=> refactor: combine WorkspaceContext and WorkspaceMemberContext to WorkspaceDirectory

Cargo.lock, Cargo.toml, src/workspace/mod.rs, src/workspace/resolver.rs
Moved from https://github.com/denoland/deno_graph/pull/509
This is in order to support workspace jsr resolution in deno compile as we don't use deno_graph for that code.
This code living here will make more sense once we rename this repo to deno_workspace.
=> feat: add workspace jsr pkg resolution

src/deno_json/ts.rs
This will be on by default via "strict"
=> feat: allow new strictBuiltinIteratorReturn compiler option

src/deno_json/mod.rs, src/workspace/mod.rs
I'm not really a fan of this code existing here in deno_config, but I don't have time to refactor it into the CLI atm.
This allows me to upgrade to TypeScript 5.6.
=> fix: use NodeNext resolution in compiler options

Cargo.lock, Cargo.toml, src/deno_json/mod.rs, src/workspace/mod.rs, src/workspace/resolver.rs
This is for security reasons for the time being for Deno 2. Details to follow post Deno 2.0 release.
Remote import maps seem incredibly rare (only 1 usage on GitHub from what I can tell!), so we'll add this back with more permissions if there's enough demand for it: https://github.com/search?type=code&q=%2F%22importMap%22%3A+%22http%2F
In the meantime, use the `--import-map` flag and `"deno.importMap"` config in the LSP.
=> BREAKING: remove support for remote import maps specified in the config

Cargo.lock, Cargo.toml, src/workspace/mod.rs, src/workspace/resolver.rs
Removes a panic and adds a new diagnostic for invalid workspace member name:
```
➜ denod task 
Warning invalid workspace member "@tst/a/b". The name should match the pattern "^@[a-z0-9-]+/[a-z0-9-]+$".
at file:///Users/sr/c/denoland/deno/tst/a/deno.json
Available tasks:
No tasks found in configuration file
```
Towards https://github.com/denoland/deno/issues/26334
=> fix: don't panic for invalid package name

src/deno_json/mod.rs
https://github.com/denoland/deno_config/pull/129 will add support for 
defining tasks using object notation and support `description` field,
which renders support for comments in tasks not needed. This greatly
simplifies the code.
=> feat: remove support for comments in 'tasks' option

src/workspace/mod.rs
Forgot to push it to https://github.com/denoland/deno_config/pull/129 before releasing.
=> fix(task): make TaskDefinition public

src/deno_json/mod.rs, src/workspace/mod.rs, src/workspace/resolver.rs
It's easier for someone to provide a sys implementation than having to provide a closure.
=> refactor: use sys_traits for reading from import map

Cargo.lock, Cargo.toml, src/workspace/mod.rs, src/workspace/resolver.rs
Downstream: https://github.com/denoland/deno/pull/27844.
=> feat: support "compilerOptions.rootDirs"

src/deno_json/ts.rs, src/workspace/resolver.rs
I missed this somehow.
Ref https://github.com/denoland/deno/pull/27844.
=> fix: don't warn on "compilerOptions.rootDirs"

src/deno_json/mod.rs, src/deno_json/ts.rs, src/workspace/mod.rs
Resolves the jsx config only on the workspace member. There was some places in the CLI that was getting it from the wrong place.
=> fix: better jsx config resolution

src/workspace/mod.rs
This will make deno_graph import this as a dependency.
Part of https://github.com/denoland/deno/issues/28221
=> fix: resolve default jsxImportSource for jsx automatic

src/workspace/mod.rs
towards https://github.com/denoland/deno/issues/28455
This PR tries to update `WorkspaceDirectory.to_raw_user_provided_tsconfig` method. The method now reads `compilerOptions` from `tsconfig.json` next to `package.json` if exists.
=> feat(workspace): read compiler options from tsconfig.json next to package.json
