src/lib.rs
Cause of https://github.com/denoland/deno/actions/runs/6047722006/job/16411706360, ref https://github.com/denoland/deno/pull/20347.
=> fix: use specifier_to_file_path() when resolving lockfile

src/lib.rs
=> fix: allow remote modules in FilesConfig::matches_specifier()

Cargo.lock, Cargo.toml
Noticed this in Deno's lockfile.
=> fix: remove deno_semver dependency

src/lib.rs
I think this will help be a bit less verbose.
=> feat: add has_unstable helper method

src/lib.rs
Add an option for `publish.exclude` and `publish.include`.
=> feat: add `publish.exclude` / `publish.include` option

src/glob.rs
For https://github.com/denoland/deno/issues/22239
=> fix: normalize path when joining on base

src/lib.rs
Also pushing down from the CLI.
=> feat: to_workspace_members

src/lib.rs
This is moved down from the CLI
=> feat: resolve_export_value_urls

src/glob.rs, src/lib.rs
Some preparation for upcoming include/exclude improvement.
=> perf: reduce work resolving excludes

src/lib.rs
Fixing https://github.com/denoland/deno/issues/23343
=> fix: look for deno.json and deno.jsonc for workspace members

src/lib.rs
It was creating file urls like `file:///some_path/../import_map.json`
Part of https://github.com/denoland/deno/issues/23057
=> fix: normalize import map path

src/lib.rs
Instead error if it's empty.
Also rename the field to `workspace`. I used `#[serde(alias = "workspaces")]` instead of `#[serde(rename = "workspaces")]`, meaning that the new proposed name would be allowed for users.
=> feat: make workspaces field nullable

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, clippy.toml, src/deno_json/mod.rs, src/deno_json/ts.rs, src/fs.rs, src/lib.rs, src/package_json.rs, src/sync.rs, src/util.rs
Moves this down from the CLI with some changes.
CLI PR: https://github.com/denoland/deno/pull/24348
Split out from https://github.com/denoland/deno_config/pull/58
=> feat: add PackageJson

src/workspace/mod.rs
Switching the 'workspaces' diagnostic to be non-fatal so that people can still keep developing deno_std with the currently released version of deno.
=> fix: change 'workspaces' diagnostic to non-fatal

src/workspace/discovery.rs, src/workspace/mod.rs
Moves the fatal diagnostic to just be an error on discovery.
=> feat: remove fatal diagnostics

Cargo.lock, Cargo.toml, src/deno_json/mod.rs, src/fs.rs, src/glob/collector.rs, src/glob/gitignore.rs, src/glob/mod.rs, src/package_json.rs
Moved from the CLI.
CLI PR: https://github.com/denoland/deno/pull/24433
=> feat: move `FileCollector` to deno_config

src/workspace/mod.rs
For https://github.com/denoland/deno/issues/24531
=> fix: use start directory deno.json as "root deno.json config" in npm workspace

src/workspace/mod.rs
Part of https://github.com/denoland/deno/issues/24519
=> feat: move imports w/ importMap diagnostic to deno_config

src/deno_json/mod.rs, src/workspace/mod.rs, src/workspace/resolver.rs
Helps reduce clones in the CLI.
=> fix: fetch_text should be FnOnce

Cargo.lock, Cargo.toml
I didn't realize the CI publish failed.
=> fix: use ci published version of deno_package_json

README.md
This pullrequest updates the old URL link in the README file.
=> docs: update URL link in README.md

src/glob/mod.rs
For https://github.com/denoland/deno/pull/25001
=> fix: handle jsr and npm specifiers when globbing

src/deno_json/mod.rs, src/workspace/mod.rs
```json
{
"nodeModules": "local-auto"
}
```
For 2.0
=> feat: Add nodeModules config option

src/deno_json/mod.rs, src/workspace/mod.rs
1. Merges "nodeModules" into "nodeModulesDir"
2. Makes the options "auto", "manual", and "none" while maintaining backwards compat with true and false.
=> feat: merge "nodeModules" into "nodeModulesDir"

src/workspace/mod.rs
For the future. I forgot to commit this one in the last pr.
=> refactor: rename node_modules_dir_mode() to node_modules_dir()

src/workspace/discovery.rs, src/workspace/mod.rs
For https://github.com/denoland/deno/issues/25847
=> fix: handle when specified config is workspace root

src/workspace/discovery.rs, src/workspace/mod.rs
Towards https://github.com/denoland/deno/issues/25783
=> feat: support for wildcards in deno.json workspace members

src/workspace/mod.rs
Landed without formatting by mistake https://github.com/denoland/deno_config/actions/runs/11671498838/job/32498018255
=> chore: format

src/deno_json/mod.rs, src/workspace/mod.rs
Towards https://github.com/denoland/deno/issues/28747.
=> feat: resolve plugin paths from config specifier

src/workspace/mod.rs
For https://github.com/denoland/deno/pull/29092
=> fix(tsconfig): do not warn for not found errors

src/deno_json/mod.rs, src/workspace/discovery.rs, src/workspace/mod.rs
Part of https://github.com/denoland/deno/issues/29468
I think plural makes sense because all our other fields are plural and this supports more than one link.
=> feat: rename "patch" property to "links"
